[versions]
download = "5.6.0"
junit = "6.0.2"
nexus-staging-version = "0.30.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
download = { id = "de.undercouch.download", version.ref = "download" }
nexus-staging = { id = "io.codearte.nexus-staging", version.ref = "nexus-staging-version" }
